add_newline = false
# A minimal left prompt
format = """$username$directory$character"""
palette = "catppuccin_mocha"

# Move important information to the right
right_format = """
$git_branch \
$git_state\
$git_status\
$cmd_duration
"""
command_timeout = 1000

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'

[directory]
style = "blue"

[username]
style_user = 'green dimmed'
style_root = 'red bold'
format = '[$user]($style)@'
disabled = false
show_always = true

[cmd_duration]
min_time = 1000
show_milliseconds = false
disabled = false
format = "($duration($style))"
style = "bold italic #87A752"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
